# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# category0=Category.create(:Name => '#{Trekking}', :Description => '#{<h5>Trekking in Nepal</h5><div class="border"></div><p>With eight of the top ten highest summits in the world and some of the most beautiful landscapes which are only reachable on foot, trekking in Nepal is one of the unique experiences of Asia. Trekking is the most popular activity in Nepal, and travellers will be bombarded on the streets of Kathmandu and the trekking hub, Pokhara, with guides, organised tours and gear for sale or rent. The huge variety of options allows for people of many ages and capabilities to attempt a trek in the country. While you could spend a year planning an expedition to wild and lofty places that few would dare attempt, you could also arrive in Kathmandu with no plans and be on the trail in a matter of days. </p>}', :icon => '#{trek-icon.png}', :slug => '#{trekking}, , :Order => '#{1}')


# item0=category0.items.create(:Name => '#{Trekking}', :Description => '#{<h5>Trekking in Nepal</h5><div class="border"></div><p>With eight of the top ten highest summits in the world and some of the most beautiful landscapes which are only reachable on foot, trekking in Nepal is one of the unique experiences of Asia. Trekking is the most popular activity in Nepal, and travellers will be bombarded on the streets of Kathmandu and the trekking hub, Pokhara, with guides, organised tours and gear for sale or rent. The huge variety of options allows for people of many ages and capabilities to attempt a trek in the country. While you could spend a year planning an expedition to wild and lofty places that few would dare attempt, you could also arrive in Kathmandu with no plans and be on the trail in a matter of days. </p>}', :Order => '#{1}')

# images0=item0.images.create(:Name => '#{pic}', :Content => '#{many trekkers prefer to overnight at one of the lower villages on their way to Ghorepani, covering the distance over two days owing to the steepness of the trail, the increase in altitude and the beauty of the natural surroundings}', :Order => '#{1}', :image =>'#{/uploads/image/image/1/trek3.png}')
# descriptions0=item0.descriptions.create(:Name => '#{trek}', :Content => '#{The place used to be a rest stop where ancient traders found water (pani in Nepali) for their horses (ghora in Nepali) thus leading to the nomenclature Ghorepani.}', :Order => '#{1}')
# item1=category0.items.create(:Name => '#{Trekking}', :Description => '#{<h5>Trekking in Nepal</h5><div class="border"></div><p>With eight of the top ten highest summits in the world and some of the most beautiful landscapes which are only reachable on foot, trekking in Nepal is one of the unique experiences of Asia. Trekking is the most popular activity in Nepal, and travellers will be bombarded on the streets of Kathmandu and the trekking hub, Pokhara, with guides, organised tours and gear for sale or rent. The huge variety of options allows for people of many ages and capabilities to attempt a trek in the country. While you could spend a year planning an expedition to wild and lofty places that few would dare attempt, you could also arrive in Kathmandu with no plans and be on the trail in a matter of days. </p>}', :Order => '#{1}')

# images0=item1.images.create(:Name => '#{mountain}', :Content => '#{snowy mountain for trek}', :Order => '#{8}', :image =>'#{/uploads/image/image/7/trek9.png}')
# descriptions0=item1.descriptions.create(:Name => '#{snowy }', :Content => '#{climb sherp and get helped by them}', :Order => '#{8}')
# item2=category0.items.create(:Name => '#{Trekking}', :Description => '#{<h5>Trekking in Nepal</h5><div class="border"></div><p>With eight of the top ten highest summits in the world and some of the most beautiful landscapes which are only reachable on foot, trekking in Nepal is one of the unique experiences of Asia. Trekking is the most popular activity in Nepal, and travellers will be bombarded on the streets of Kathmandu and the trekking hub, Pokhara, with guides, organised tours and gear for sale or rent. The huge variety of options allows for people of many ages and capabilities to attempt a trek in the country. While you could spend a year planning an expedition to wild and lofty places that few would dare attempt, you could also arrive in Kathmandu with no plans and be on the trail in a matter of days. </p>}', :Order => '#{1}')

# images0=item2.images.create(:Name => '#{dolpa to trek}', :Content => '#{Dolpa is the largest district of Nepal covering 5.36% of the total landmass of the country, located at 28°43’N to 29°43’N latitude, and 82°23’E to 83°41’E longitude. Elevation ranges from 1,525 to 7,625 m (5,003 to 25,016 ft).}', :Order => '#{9}', :image =>'#{/uploads/image/image/10/trek7.png}')
# descriptions0=item2.descriptions.create(:Name => '#{upper dolpa}', :Content => '#{ The district borders Tibet ( China) on the north and northeast, Jumla and Mugu districts of Karnali on the west, Myagdi, Jajarkot and Rukum on the south, and Mustang on the east}', :Order => '#{3}')
# item3=category0.items.create(:Name => '#{Trekking}', :Description => '#{<h5>Trekking in Nepal</h5><div class="border"></div><p>With eight of the top ten highest summits in the world and some of the most beautiful landscapes which are only reachable on foot, trekking in Nepal is one of the unique experiences of Asia. Trekking is the most popular activity in Nepal, and travellers will be bombarded on the streets of Kathmandu and the trekking hub, Pokhara, with guides, organised tours and gear for sale or rent. The huge variety of options allows for people of many ages and capabilities to attempt a trek in the country. While you could spend a year planning an expedition to wild and lofty places that few would dare attempt, you could also arrive in Kathmandu with no plans and be on the trail in a matter of days. </p>}', :Order => '#{1}')

# images0=item3.images.create(:Name => '#{makalu,nepal}', :Content => '#{Makalu has two notable subsidiary peaks. Kangchungtse, or Makalu II (7,678 m) lies about 3 km (2 mi) north-northwest of the main summit. Rising about 5 km (3.1 mi) north-northeast of the main summit across a broad plateau, and connected to Kangchungtse by a narrow, 7,200 m saddle, is Chomo Lonzo (7,804 m).}', :Order => '#{8}', :image =>'#{/uploads/image/image/11/trek6.png}')
# descriptions0=item3.descriptions.create(:Name => '#{trek}', :Content => '#{Makalu has two notable subsidiary peaks. Kangchungtse, or Makalu II (7,678 m) lies about 3 km (2 mi) north-northwest of the main summit. Rising about 5 km (3.1 mi) north-northeast of the main summit across a broad plateau, and connected to Kangchungtse by a narrow, 7,200 m saddle, is Chomo Lonzo (7,804 m).}', :Order => '#{7}')
# category1=Category.create(:Name => '#{Tourism}', :Description => '#{<h5>Tourism in Nepal</h5><div class="border"></div><p>Nepal is the country where Mount Everest, the highest mountain peak in the world, is located. Mountaineering and other types of adventure tourism and ecotourism are important attractions for visitors. The world heritage site Lumbini, birthplace of Gautama Buddha, is located in southern Nepal, and there are other important religious pilgrimage sites throughout the country.</p>}', :icon => '#{tour-icon.png}', :slug => '#{tourism}, , :Order => '#{2}')


# item0=category1.items.create(:Name => '#{Tourism}', :Description => '#{<h5>Tourism in Nepal</h5><div class="border"></div><p>Nepal is the country where Mount Everest, the highest mountain peak in the world, is located. Mountaineering and other types of adventure tourism and ecotourism are important attractions for visitors. The world heritage site Lumbini, birthplace of Gautama Buddha, is located in southern Nepal, and there are other important religious pilgrimage sites throughout the country.</p>}', :Order => '#{2}')

# images0=item0.images.create(:Name => '#{temple}', :Content => '#{The temple is one of the 275 Paadal Petra Sthalams (Holy Abodes of Shiva) on the continent. Over the past times, only born Hindus were allowed to enter the temple. Others could look at it from other side of the river. However, the norms have been relaxed due to many incident.}', :Order => '#{2}', :image =>'#{/uploads/image/image/2/tourisum5.png}')
# descriptions0=item0.descriptions.create(:Name => '#{temple}', :Content => '#{Pashupatinath Temple is the oldest Hindu temple in Kathmandu. It is not known for certain when Pashupatinath Temple was founded. But according to Nepal Mahatmaya and Himvatkhanda,[4] the deity here gained great fame there as Pashupati, the Lord of all Pashus, which are living as well as non-living beings.}', :Order => '#{2}')
# item1=category1.items.create(:Name => '#{Tourism}', :Description => '#{<h5>Tourism in Nepal</h5><div class="border"></div><p>Nepal is the country where Mount Everest, the highest mountain peak in the world, is located. Mountaineering and other types of adventure tourism and ecotourism are important attractions for visitors. The world heritage site Lumbini, birthplace of Gautama Buddha, is located in southern Nepal, and there are other important religious pilgrimage sites throughout the country.</p>}', :Order => '#{2}')

# images0=item1.images.create(:Name => '#{durbar}', :Content => '#{Patan Durbar Square is situated at the centre of Lalitpur city. It is one of the three Durbar Squares in the Kathmandu Valley, all of which are UNESCO World Heritage Sites. One of its attraction is The Ancient Royal Palace where Malla Kings of Lalitpur resided. The Durbar Square is a marvel of Newa architecture. The Square floor is tiled with red bricks.[1] There are many temples and idols in the area. The main temples are aligned opposite of the western face of the palace.[2] The entrance of the temples faces east, towards the palace.}', :Order => '#{5}', :image =>'#{/uploads/image/image/9/tourisum3.png}')
# descriptions0=item1.descriptions.create(:Name => '#{palace}', :Content => '#{<p>Patan Durbar Square is situated at the centre of Lalitpur city. It is one of the three Durbar Squares in the Kathmandu Valley, all of which are UNESCO World Heritage Sites. One of its attraction is The Ancient Royal Palace where Malla Kings of Lalitpur resided.</p> }', :Order => '#{4}')
# item2=category1.items.create(:Name => '#{Tourism}', :Description => '#{<h5>Tourism in Nepal</h5><div class="border"></div><p>Nepal is the country where Mount Everest, the highest mountain peak in the world, is located. Mountaineering and other types of adventure tourism and ecotourism are important attractions for visitors. The world heritage site Lumbini, birthplace of Gautama Buddha, is located in southern Nepal, and there are other important religious pilgrimage sites throughout the country.</p>}', :Order => '#{2}')

# images0=item2.images.create(:Name => '#{maya devi temple}', :Content => '#{Lumbini has a number of temples, including the Mayadevi Temple and several others which are still under construction. Many monuments, monasteries and a museum — the Lumbini International Research Institute — are also located within the holy site. Also located there is the Puskarini or Holy Pond where the Buddha's mother took the ritual dip prior to his birth and where he, too, had his first bath. At other sites near Lumbini, earlier Buddhas were, according to tradition, born, achieved ultimate Enlightenment and finally relinquished their earthly forms.}', :Order => '#{4}', :image =>'#{/uploads/image/image/8/tourisum4.png}')
# descriptions0=item2.descriptions.create(:Name => '#{shanti deep}', :Content => '#{Lumbini has a number of temples, including the Mayadevi Temple and several others which are still under construction. Many monuments, monasteries and a museum — the Lumbini International Research Institute — are also located within the holy site. Also located there is the Puskarini or Holy Pond where the Buddha's mother took the ritual dip prior to his birth and where he, too, had his first bath. At other sites near Lumbini, earlier Buddhas were, according to tradition, born, achieved ultimate Enlightenment and finally relinquished their earthly forms.}', :Order => '#{4}')
# descriptions1=item2.descriptions.create(:Name => '#{}', :Content => '#{}', :Order => '#{}')
# descriptions2=item2.descriptions.create(:Name => '#{}', :Content => '#{}', :Order => '#{}')
# item3=category1.items.create(:Name => '#{Tourism}', :Description => '#{<h5>Tourism in Nepal</h5><div class="border"></div><p>Nepal is the country where Mount Everest, the highest mountain peak in the world, is located. Mountaineering and other types of adventure tourism and ecotourism are important attractions for visitors. The world heritage site Lumbini, birthplace of Gautama Buddha, is located in southern Nepal, and there are other important religious pilgrimage sites throughout the country.</p>}', :Order => '#{2}')

# images0=item3.images.create(:Name => '#{temple}', :Content => '#{The Budanilkantha statue of the Hindu god Vishnu, located approximately 10 kilometers from the center of Kathmandu at the base of the Shivapuri Hill, is the largest stone carving in all of Nepal. This particular statue of Lord Vishnu is taken as the most relaxed avatar of Lord Vishnu. People often describe the placidity around the temple as "very relaxing".}', :Order => '#{7}', :image =>'#{/uploads/image/image/12/tourisum9.png}')
# descriptions0=item3.descriptions.create(:Name => '#{tourism temple}', :Content => '#{The Budanilkantha statue of the Hindu god Vishnu, located approximately 10 kilometers from the center of Kathmandu at the base of the Shivapuri Hill, is the largest stone carving in all of Nepal. This particular statue of Lord Vishnu is taken as the most relaxed avatar of Lord Vishnu. People often describe the placidity around the temple as "very relaxing".}', :Order => '#{6}')
# item4=category1.items.create(:Name => '#{Tourism}', :Description => '#{<h5>Tourism in Nepal</h5><div class="border"></div><p>Nepal is the country where Mount Everest, the highest mountain peak in the world, is located. Mountaineering and other types of adventure tourism and ecotourism are important attractions for visitors. The world heritage site Lumbini, birthplace of Gautama Buddha, is located in southern Nepal, and there are other important religious pilgrimage sites throughout the country.</p>}', :Order => '#{2}')

# images0=item4.images.create(:Name => '#{chitwan bharatpur}', :Content => '#{The district takes its name from the Chitwan Valley, one of Nepal's Inner Terai valleys between the Mahabharat and Siwalik ranges, both considered foothills of the Himalayas. Now there are about 40 Village Development Committees, each of which has nine wards or villages and one sub-Metropolitan city, Bharatpur. The Ratnanagar, Khairhani and Chitrawan municipalities have more than nine wards or urban areas.}', :Order => '#{5}', :image =>'#{/uploads/image/image/19/tourisum12.png}')
# descriptions0=item4.descriptions.create(:Name => '#{sauraha}', :Content => '#{Bharatpur is located on the banks of the Narayani River, and is the main town with numerous shopping zones where people come from all over the district and neighbouring districts.}', :Order => '#{9}')
# category2=Category.create(:Name => '#{Culture}', :Description => '#{<h5>Culture in Nepal</h5><div class="border"></div><p>Kathmandu Valley has served as the country's cultural metropolis since the unification of Nepal in the 18th Century. A prominent factor in a Nepali's everyday life is religion. Adding color to the lives of Nepalis are festivals the year round which they celebrate with much pomp and joy.</p>}', :icon => '#{culture-icon.png}', :slug => '#{culture}, , :Order => '#{3}')


# item0=category2.items.create(:Name => '#{Culture}', :Description => '#{<h5>Culture in Nepal</h5><div class="border"></div><p>Kathmandu Valley has served as the country's cultural metropolis since the unification of Nepal in the 18th Century. A prominent factor in a Nepali's everyday life is religion. Adding color to the lives of Nepalis are festivals the year round which they celebrate with much pomp and joy.</p>}', :Order => '#{3}')

# images0=item0.images.create(:Name => '#{stupa}', :Content => '#{The Swayambhunath complex consists of a stupa, a variety of shrines and temples, some dating back to the Licchavi period.}', :Order => '#{3}', :image =>'#{/uploads/image/image/3/tourisum2.png}')
# descriptions0=item0.descriptions.create(:Name => '#{ghumba}', :Content => '#{The stupa has Buddha's eyes and eyebrows painted on. Between them, the number one (in Devanagari script) is painted in the fashion of a nose.}', :Order => '#{3}')
# item1=category2.items.create(:Name => '#{Culture}', :Description => '#{<h5>Culture in Nepal</h5><div class="border"></div><p>Kathmandu Valley has served as the country's cultural metropolis since the unification of Nepal in the 18th Century. A prominent factor in a Nepali's everyday life is religion. Adding color to the lives of Nepalis are festivals the year round which they celebrate with much pomp and joy.</p>}', :Order => '#{3}')

# images0=item1.images.create(:Name => '#{stupa}', :Content => '#{Shanti Stupa is a Buddhist white-domed stupa (chorten) on a hilltop in Chanspa, Leh district, Ladakh, in the north Indian state of Jammu and Kashmir.[1] It was built in 1991 by Japanese Buddhist Bhikshu, Gyomyo Nakamura and part of the Peace Pagoda mission}', :Order => '#{4}', :image =>'#{/uploads/image/image/13/tourisum8.png}')
# descriptions0=item1.descriptions.create(:Name => '#{ghumba}', :Content => '#{Shanti Stupa is a Buddhist white-domed stupa (chorten) on a hilltop in Chanspa, Leh district, Ladakh, in the north Indian state of Jammu and Kashmir.[1] It was built in 1991 by Japanese Buddhist Bhikshu, Gyomyo Nakamura and part of the Peace Pagoda mission}', :Order => '#{7}')
# item2=category2.items.create(:Name => '#{Culture}', :Description => '#{<h5>Culture in Nepal</h5><div class="border"></div><p>Kathmandu Valley has served as the country's cultural metropolis since the unification of Nepal in the 18th Century. A prominent factor in a Nepali's everyday life is religion. Adding color to the lives of Nepalis are festivals the year round which they celebrate with much pomp and joy.</p>}', :Order => '#{3}')

# images0=item2.images.create(:Name => '#{temple}', :Content => '#{ The temple is located in Changunarayan VDC of Bhaktapur District, Nepal. This hill is about 8 miles east of Kathmandu and a few miles north of Bhaktapur. The Manahara River flows beside the hill. This shrine is dedicated to Lord Visnu and held in especial reverence by the Hindu people. This temple is considered as the oldest temple in Nepal.}', :Order => '#{4}', :image =>'#{/uploads/image/image/14/tourisum11.png}')
# descriptions0=item2.descriptions.create(:Name => '#{temple}', :Content => '#{The pagoda style temple has several masterpieces of 5th and 12th century Nepalese art. According to legends Changu Narayan temple existed as early as 325 A.D. in the time of King Licchavi King Hari Datta Verma and it is one of Nepal's richest structures historically as well as artistically}', :Order => '#{3}')
# descriptions1=item2.descriptions.create(:Name => '#{worship}', :Content => '#{In ancient time a Gwala, a cow herder, had brought a cow from a Brahman named Sudarshan. The cow was known for producing large quantity of milk. The Gwala used to take the cow to Changu for grazing. At that time Changu was a forest of Champak tree. While grazing the cow it always went to the shade of a particular tree. In the evening when the Gwala took the cow home and started milking the cow he got only very few amount of milk. This continued several days. He became very sad so he called the Brahmin and told him that the cow is not giving enough milk. Brahmin after observing the fact from his own eyes then planned with the Gwala to inspect the activities of cow during the day while she was grazing in the forest. Both Brahmin and Gwala hide themselves behind the trees and spectate the activities of the cow. The cow went into the shade of a particular champak tree. To their surprise a small black boy came out from the tree and started drinking the cow milk. Both became very furious and they thought that the boy must be the devil and tree must be its home. }', :Order => '#{4}')
# item3=category2.items.create(:Name => '#{Culture}', :Description => '#{<h5>Culture in Nepal</h5><div class="border"></div><p>Kathmandu Valley has served as the country's cultural metropolis since the unification of Nepal in the 18th Century. A prominent factor in a Nepali's everyday life is religion. Adding color to the lives of Nepalis are festivals the year round which they celebrate with much pomp and joy.</p>}', :Order => '#{3}')

# images0=item3.images.create(:Name => '#{old area}', :Content => '#{The Hanuman Dhoka Palace Museum is a museum housed in the Hanuman Dhoka Palace in Kathmandu. It is run by the Nepalese government. The museum is part of the larger Hanuman Dhoka Palace complex, which is known as Hanuman Dhoka Durbar in Nepali. The palace gets its name from the stone image of Hanuman, the Hindu monkey god, that sits near the main entryway. 'Dhoka' means door in Nepali.[1]}', :Order => '#{5}', :image =>'#{/uploads/image/image/15/tourisum1.png}')
# images1=item3.images.create(:Name => '#{old heritage}', :Content => '#{The Hanuman Dhoka Palace Museum is a museum housed in the Hanuman Dhoka Palace in Kathmandu. The palace gets its name from the stone image of Hanuman, the Hindu monkey god, that sits near the main entryway. 'Dhoka' means door in Nepali.[1] . The museum is part of the larger Hanuman Dhoka Palace complex, which is known as Hanuman Dhoka Durbar in Nepali}', :Order => '#{6}', :image =>'#{/uploads/image/image/16/tourisum3.png}')
# descriptions0=item3.descriptions.create(:Name => '#{meusuem}', :Content => '#{The museum is part of the larger Hanuman Dhoka Palace complex, which is known as Hanuman Dhoka Durbar in Nepali}', :Order => '#{6}')
# item4=category2.items.create(:Name => '#{Culture}', :Description => '#{<h5>Culture in Nepal</h5><div class="border"></div><p>Kathmandu Valley has served as the country's cultural metropolis since the unification of Nepal in the 18th Century. A prominent factor in a Nepali's everyday life is religion. Adding color to the lives of Nepalis are festivals the year round which they celebrate with much pomp and joy.</p>}', :Order => '#{3}')

# images0=item4.images.create(:Name => '#{palace}', :Content => '#{The square is still the center of important royal events like the coronation of King Birendra Bir Bikram Shah in 1975 and King Gyanendra Bir Bikram Shah in 2001. Though there are no written archives stating the history of Kathmandu Durbar Square, construction of the palace in the square is credited to Sankharadev (1069–1083). As the first king of the independent Kathmandu City, Ratna Malla is said to have built the Taleju temple in the Northern side of the palace in 1501. For this to be true then the temple would have had to have been built in the vihara style as part of the palace premise surrounding the Mul Chok courtyard for no evidence of a separate structure that would match this temple can be found within the square}', :Order => '#{6}', :image =>'#{/uploads/image/image/20/tourisum3.png}')
# images1=item4.images.create(:Name => '#{roam}', :Content => '#{Northern side of the palace in 1501. For this to be true then the temple would have had to have been built in the vihara style as part of the palace premise surrounding the Mul Chok courtyard for no evidence of a separate structure that would match this temple can be found within the square}', :Order => '#{7}', :image =>'#{/uploads/image/image/21/tourisum7.png}')
# images2=item4.images.create(:Name => '#{made of wood}', :Content => '#{Northern side of the palace in 1501. For this to be true then the temple would have had to have been built in the vihara style as part of the palace premise surrounding the Mul Chok courtyard for no evidence of a separate structure that would match this temple can be found within the square}', :Order => '#{8}', :image =>'#{/uploads/image/image/22/tourisum5.png}')
# descriptions0=item4.descriptions.create(:Name => '#{historical place}', :Content => '#{Northern side of the palace in 1501. For this to be true then the temple would have had to have been built in the vihara style as part of the palace premise surrounding the Mul Chok courtyard for no evidence of a separate structure that would match this temple can be found within the square}', :Order => '#{2}')
# descriptions1=item4.descriptions.create(:Name => '#{entry}', :Content => '#{Northern side of the palace in 1501. For this to be true then the temple would have had to have been built in the vihara style as part of the palace premise surrounding the Mul Chok courtyard for no evidence of a separate structure that would match this temple can be found within the square}', :Order => '#{5}')
# descriptions2=item4.descriptions.create(:Name => '#{sound place}', :Content => '#{Northern side of the palace in 1501. For this to be true then the temple would have had to have been built in the vihara style as part of the palace premise surrounding the Mul Chok courtyard for no evidence of a separate structure that would match this temple can be found within the square}', :Order => '#{5}')
# category3=Category.create(:Name => '#{Business}', :Description => '#{<h5>Business in Nepal</h5><div class="border"></div><p>An isolated, agrarian society until the mid-20th century, Nepal entered the modern era in 1951 without schools, hospitals, roads, telecommunications, electric power, industry, or civil service. The country has, however, made progress toward sustainable economic growth since the 1950s and is committed to a program of economic liberalization. Nepal has used a series of five-year plans in an attempt to make progress in economic development. It completed its ninth economic development plan in 2002; its currency has been made convertible, and 17 state enterprises have been privatized. Foreign aid accounts for more than half of the development budget. Government priorities over the years have been the development of transportation and communication facilities, agriculture, and industry. Since 1975, improved government administration and rural development efforts have been emphasized.</p>}', :icon => '#{business-icon.png}', :slug => '#{business}, , :Order => '#{4}')


# item0=category3.items.create(:Name => '#{Business}', :Description => '#{<h5>Business in Nepal</h5><div class="border"></div><p>An isolated, agrarian society until the mid-20th century, Nepal entered the modern era in 1951 without schools, hospitals, roads, telecommunications, electric power, industry, or civil service. The country has, however, made progress toward sustainable economic growth since the 1950s and is committed to a program of economic liberalization. Nepal has used a series of five-year plans in an attempt to make progress in economic development. It completed its ninth economic development plan in 2002; its currency has been made convertible, and 17 state enterprises have been privatized. Foreign aid accounts for more than half of the development budget. Government priorities over the years have been the development of transportation and communication facilities, agriculture, and industry. Since 1975, improved government administration and rural development efforts have been emphasized.</p>}', :Order => '#{4}')

# images0=item0.images.create(:Name => '#{pic}', :Content => '#{company and solution }', :Order => '#{4}', :image =>'#{/uploads/image/image/4/tourisum14.png}')
# descriptions0=item0.descriptions.create(:Name => '#{business}', :Content => '#{company and solution When trying to be the best, strong support is needed, a dependable team is a necessity. }', :Order => '#{4}')
# item1=category3.items.create(:Name => '#{Business}', :Description => '#{<h5>Business in Nepal</h5><div class="border"></div><p>An isolated, agrarian society until the mid-20th century, Nepal entered the modern era in 1951 without schools, hospitals, roads, telecommunications, electric power, industry, or civil service. The country has, however, made progress toward sustainable economic growth since the 1950s and is committed to a program of economic liberalization. Nepal has used a series of five-year plans in an attempt to make progress in economic development. It completed its ninth economic development plan in 2002; its currency has been made convertible, and 17 state enterprises have been privatized. Foreign aid accounts for more than half of the development budget. Government priorities over the years have been the development of transportation and communication facilities, agriculture, and industry. Since 1975, improved government administration and rural development efforts have been emphasized.</p>}', :Order => '#{4}')

# images0=item1.images.create(:Name => '#{hotel}', :Content => '#{You can be sure to find the most up-to-date information and hotel deals here. With 14 different regions, the country offers its visitors a great diversity of beautiful landscapes as well as a vibrant culture and lifestyle}', :Order => '#{9}', :image =>'#{/uploads/image/image/17/hotel-img.png}')
# descriptions0=item1.descriptions.create(:Name => '#{eat and rest}', :Content => '#{You can be sure to find the most up-to-date information and hotel deals here. With 14 different regions, the country offers its visitors a great diversity of beautiful landscapes as well as a vibrant culture and lifestyle}', :Order => '#{4}')
# category4=Category.create(:Name => '#{Legal}', :Description => '#{<h5>Law in Nepal</h5><div class="border"></div><p>The Copyright law of Nepal governs copyright, the right to control the use and distribution of artistic and creative works in Nepal and also encourages the creation of art and culture by rewarding authors and artists with a set of exclusive rights.[1] It is embodied in the Copyright Act, 2059 (2002), the Copyright Rule, 2061 (2004) and their amendments. Nepal Copyright Registrar's Office handles copyright registration, recording of copyright transfers and other administrative aspects of copyright law.</p>}', :icon => '#{law-icon.png}', :slug => '#{legal}, , :Order => '#{5}')


# item0=category4.items.create(:Name => '#{Legal}', :Description => '#{<h5>Law in Nepal</h5><div class="border"></div><p>The Copyright law of Nepal governs copyright, the right to control the use and distribution of artistic and creative works in Nepal and also encourages the creation of art and culture by rewarding authors and artists with a set of exclusive rights.[1] It is embodied in the Copyright Act, 2059 (2002), the Copyright Rule, 2061 (2004) and their amendments. Nepal Copyright Registrar's Office handles copyright registration, recording of copyright transfers and other administrative aspects of copyright law.</p>}', :Order => '#{5}')

# images0=item0.images.create(:Name => '#{law}', :Content => '#{The Supreme Court of Nepal (Nepali: सर्वोच्च अदालत) is the highest court in Nepal. It has ultimate appellate jurisdiction over all Appellate and District court. The court consists of fourteen Justices and one Chief Justice}', :Order => '#{5}', :image =>'#{/uploads/image/image/5/law-img.jpg}')
# descriptions0=item0.descriptions.create(:Name => '#{legal}', :Content => '#{The Supreme Court of Nepal (Nepali: सर्वोच्च अदालत) is the highest court in Nepal. It has ultimate appellate jurisdiction over all Appellate and District court. The court consists of fourteen Justices and one Chief Justice}', :Order => '#{5}')
# item1=category4.items.create(:Name => '#{Legal}', :Description => '#{<h5>Law in Nepal</h5><div class="border"></div><p>The Copyright law of Nepal governs copyright, the right to control the use and distribution of artistic and creative works in Nepal and also encourages the creation of art and culture by rewarding authors and artists with a set of exclusive rights.[1] It is embodied in the Copyright Act, 2059 (2002), the Copyright Rule, 2061 (2004) and their amendments. Nepal Copyright Registrar's Office handles copyright registration, recording of copyright transfers and other administrative aspects of copyright law.</p>}', :Order => '#{5}')

# images0=item1.images.create(:Name => '#{legal law}', :Content => '#{Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur}', :Order => '#{8}', :image =>'#{/uploads/image/image/18/Travel-img.png}')
# descriptions0=item1.descriptions.create(:Name => '#{travel}', :Content => '#{Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur}', :Order => '#{7}')
# descriptions1=item1.descriptions.create(:Name => '#{law to travel}', :Content => '#{Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur}', :Order => '#{9}')
# descriptions2=item1.descriptions.create(:Name => '#{constitution}', :Content => '#{Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur}', :Order => '#{3}')
# descriptions3=item1.descriptions.create(:Name => '#{fact of law}', :Content => '#{Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur}', :Order => '#{}')
# category5=Category.create(:Name => '#{Visa}', :Description => '#{<h5>Visa Processing in Nepal</h5><div class="border"></div> <p>The visa policy of Nepal is relatively liberal, allowing citizens of almost all nations to obtain a tourist visa on arrival. Citizens of India do not need a visa for Nepal because the 1950 Indo-Nepal Treaty of Peace and Friendship allows free movement of people and goods between the two nations Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur .</p>}', :icon => '#{visa-icon.png}', :slug => '#{visa}, , :Order => '#{6}')


# item0=category5.items.create(:Name => '#{Visa}', :Description => '#{<h5>Visa Processing in Nepal</h5><div class="border"></div> <p>The visa policy of Nepal is relatively liberal, allowing citizens of almost all nations to obtain a tourist visa on arrival. Citizens of India do not need a visa for Nepal because the 1950 Indo-Nepal Treaty of Peace and Friendship allows free movement of people and goods between the two nations Perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur .</p>}', :Order => '#{6}')

# images0=item0.images.create(:Name => '#{visa}', :Content => '#{The Registrar is authorized to be worked as an administrative in charge of the Supreme Court. He/She is supposed to be worked according to general guidance of the Chief Justice of Nepal. All the administrative staff use the power delegated by the Registrar.}', :Order => '#{6}', :image =>'#{/uploads/image/image/6/law-img.jpg}')
# descriptions0=item0.descriptions.create(:Name => '#{process}', :Content => '#{The Registrar is authorized to be worked as an administrative in charge of the Supreme Court. He/She is supposed to be worked according to general guidance of the Chief Justice of Nepal. All the administrative staff use the power delegated by the Registrar.}', :Order => '#{6}') 